var ls;
(function (ls) {
	ls.MainScene = function() {
		return {
			"turretBullet": function() { return turretBullet },
			"EnemyTarget.y": function() { return EnemyTarget.y },
			"%22exit%22": function() { return "exit" },
			"%22hp%22": function() { return "hp" },
			"%22lessThan%22": function() { return "lessThan" },
			"%22greaterThan%22": function() { return "greaterThan" },
			"%22count1%22": function() { return "count1" },
			"turret2": function() { return turret2 },
			"Enemy3": function() { return Enemy3 },
			"base.y": function() { return base.y },
			"menubg": function() { return menubg },
			"%22tank4%22": function() { return "tank4" },
			"Enemy1": function() { return Enemy1 },
			"Enemy2": function() { return Enemy2 },
			"gameover.tank1%2Bgameover.tank2%2Bgameover.tank3%2Bgameover.tank4%2BEnemyTarget.exit": function() { return gameover.tank1+gameover.tank2+gameover.tank3+gameover.tank4+EnemyTarget.exit },
			"life.hp": function() { return life.hp },
			"gameover.coin": function() { return gameover.coin },
			"%22count2%22": function() { return "count2" },
			"Money.coin": function() { return Money.coin },
			"%22MainScene%22": function() { return "MainScene" },
			"%22greaterOrEqual%22": function() { return "greaterOrEqual" },
			"%22over%22": function() { return "over" },
			"%22lessOrEqual%22": function() { return "lessOrEqual" },
			"%22x%22%2Bgameover.tank4": function() { return "x"+gameover.tank4 },
			"turret1": function() { return turret1 },
			"%22coin%22": function() { return "coin" },
			"%22equalTo%22": function() { return "equalTo" },
			"%22x%22%2Bgameover.tank2": function() { return "x"+gameover.tank2 },
			"Money.coin-95": function() { return Money.coin-95 },
			"Enemy4": function() { return Enemy4 },
			"%22count3%22": function() { return "count3" },
			"Money.coin-50": function() { return Money.coin-50 },
			"%22tank1%22": function() { return "tank1" },
			"base": function() { return base },
			"%22x%22%2Bgameover.tank1": function() { return "x"+gameover.tank1 },
			"gameover": function() { return gameover },
			"%22tank2%22": function() { return "tank2" },
			"%22count4%22": function() { return "count4" },
			"EnemyTarget.x": function() { return EnemyTarget.x },
			"%22tank3%22": function() { return "tank3" },
			"%22x%22%2Bgameover.tank3": function() { return "x"+gameover.tank3 },
			"base.x": function() { return base.x }
		}
	};
})(ls || (ls = {}));